import * as React from 'react'

export type Language = 'fr' | 'ar' | 'en'

const translations = {
  fr: {
    home: 'Accueil',
    shop: 'Boutique',
    packs: 'Nos Packs',
    cart: 'Panier',
    cartAria: 'Afficher le panier',
    languageToggle: 'EN',
    brandTagline: 'Cosmétiques Marocains',
    heroBadge: '✦ Cosmétiques Marocains Authentiques',
    heroTitleLine1: 'Le Rituel Hammam',
    heroTitleLine2: 'de Luxe',
    heroDescription: 'Redécouvrez la tradition du hammam marocain avec nos soins naturels formulés à base des trésors de beauté du Maroc.',
    discoverPacks: 'Découvrir nos packs',
    individualProducts: 'Produits individuels',
    featuredSub: 'Nos bestsellers',
    packsPopular: 'Packs Populaires',
    viewAllProducts: 'Tout voir',
    viewAllProductsShort: 'Voir tous les produits',
    viewAllOrders: 'Voir toutes les commandes',
    noNewOrders: 'Aucune nouvelle commande',
    latestOrders: 'Dernières commandes',
    wrongCredentials: 'Email ou mot de passe incorrect',
    prepareOrder: 'Préparer',
    dispatchOrder: 'Expédier',
    deliverOrder: 'Livrer',
    cancelOrder: 'Annuler',
    statusAll: 'Toutes',
    noProducts: 'Aucun produit',
    editProduct: 'Modifier le produit',
    fillProductInfo: 'Remplissez les informations du produit',
    mainImageUrlLabel: 'Image principale (URL)',
    additionalImagesLabel: 'Images supplémentaires (une URL par ligne)',
    uploadProductImages: 'Télécharger des images du produit',
    selectProductImages: 'Cliquez pour sélectionner des images',
    selectBeforeImage: 'Sélectionner image avant',
    selectAfterImage: 'Sélectionner image après',
    uploadBeforeImageLabel: 'Télécharger Image Avant',
    uploadAfterImageLabel: 'Télécharger Image Après',
    productDescription: 'Description',
    productIngredients: 'Ingrédients',
    productsTitle: 'Produits',
    trustTitle: 'Elles nous font confiance',
    trustHeading: 'Avis de nos clientes',
    review1Text: 'Le pack Aker Fassi est incroyable ! Ma peau n\'a jamais été aussi douce et lumineuse. Je recommande vivement.',
    review2Text: 'Qualité exceptionnelle, produits 100% naturels. Le gommage est le meilleur que j\'ai utilisé. Livraison rapide!',
    review3Text: 'J\'achète le pack Nila chaque mois. L\'huile capillaire a transformé mes cheveux. Merci Dar Nour!',
    review4Text: 'L\'huile de prunes a redonné de l\'éclat à mon teint en quelques jours seulement.',
    review5Text: 'Service client attentionné et livraison ultra rapide. Je suis fan de la routine hammam.',
    review6Text: 'La texture est divine et les arômes sont si apaisants. Mes proches m\'ont demandé la marque !',
    review7Text: 'Mes cheveux sont plus doux et plus forts après seulement deux utilisations du pack. Un vrai soin luxe.',
    orderNowSectionTitle: 'Commandez Maintenant',
    orderNowSectionText: 'Profitez de nos offres bundle exclusives — Plus vous commandez, plus vous économisez.',
    faqSub: 'Questions fréquentes',
    faqTitle: 'Réponses claires à vos questions',
    faqDescription: 'Tout ce qu’il faut savoir pour choisir le rituel Hammam qui vous correspond.',
    faqQuestion1: 'Combien de temps dure la livraison ?',
    faqAnswer1: 'Nous livrons partout au Maroc en 2–4 jours ouvrés, avec un suivi complet de votre commande.',
    faqQuestion2: 'Les produits sont-ils vraiment naturels ?',
    faqAnswer2: 'Oui, nos soins sont formulés à partir d’ingrédients marocains authentiques, sans parabènes ni sulfates.',
    faqQuestion3: 'Puis-je commander un pack sur mesure ?',
    faqAnswer3: 'Bien sûr — contactez-nous via WhatsApp et nous préparons un rituel personnalisé selon votre besoin.',
    faqCardLabel: 'FAQ Premium',
    faqCardTitle: 'Votre routine beauté simplifiée',
    faqCardText: 'Explorez nos réponses rapides, inspirées de l’expérience de nos clientes.',
    faqCardTag1: 'Livraison rapide',
    faqCardTag2: 'Ingrédients naturels',
    faqCardStat: 'Taux de satisfaction',
    faqCardStatText: '98% de clientes satisfaites',
    ctaBadge: 'Offre Spéciale',
    ctaHeading: 'Plus de soins, plus de confiance',
    ctaText: 'Découvrez nos packs best-sellers conçus pour sublimer chaque étape de votre rituel de beauté.',
    ctaStat1Label: 'Packs disponibles',
    ctaStat1Value: '12+ options',
    ctaStat2Label: 'Satisfaction client',
    ctaStat2Value: '4.9/5',
    shopIndividual: 'Voir produits individuels',
    ctaHighlight: 'Best-sellers',
    ctaHighlightTitle: 'Rituels soigneusement sélectionnés',
    ctaHighlightDescription: 'Chacun de nos packs rassemble le meilleur de la tradition hammam et des ingrédients marocains.',
    ctaFeature1: 'Pourquoi choisir Dar Nour ?',
    ctaFeature1Text: 'Livraison express et ingrédients d’exception',
    ctaFeatureBadge: '100% naturel',
    viewOurPacks: 'Voir nos packs',
    delivery: 'Livraison Maroc',
    deliveryDesc: 'Partout au Maroc en 2–4 jours',
    natural: '100% Naturel',
    naturalDesc: 'Formules authentiques marocaines',
    quality: 'Qualité Garantie',
    qualityDesc: 'Satisfaite ou remboursée',
    productNotFound: 'Produit introuvable',
    returnToShop: 'Retour à la boutique',
    back: 'Retour',
    bestseller: 'Bestseller',
    priceLabel: 'Prix',
    stockLabel: 'Stock',
    outOfStock: 'Rupture de stock',
    packBadge: '✦ PACK',
    twoUnits: '2 unités: {price} MAD',
    threePlusUnits: '3+ unités: {price} MAD',
    stockAvailability: 'Stock: {count} disponibles',
    available: 'disponibles',
    orderSection: 'Commander',
    tierPricing: 'Tarifs dégressifs',
    quantity: 'Quantité',
    temporarilyUnavailable: 'Produit temporairement indisponible',
    addToCart: 'Ajouter au panier',
    orderNow: 'Commander maintenant',
    inYourCart: 'dans votre panier',
    ingredients: 'Ingrédients',
    shopTitle: 'Notre Boutique',
    searchPlaceholder: 'Rechercher un produit...',
    noProductsFound: 'Aucun produit trouvé',
    tryAnotherSearch: 'Essayez une autre recherche',
    productCountSingular: '1 produit',
    productCountPlural: '{count} produits',
    emptyCartTitle: 'Votre panier est vide',
    emptyCartText: 'Découvrez nos produits et commencez votre rituel beauté',
    discoverProducts: 'Découvrir nos produits',
    myCart: 'Mon Panier',
    summary: 'Récapitulatif',
    total: 'Total',
    continueShopping: 'Continuer les achats',
    checkout: 'Commander',
    cartStep: 'Panier',
    infoStep: 'Infos',
    confirmStep: 'Confirmation',
    cartEmpty: 'Panier vide',
    nameRequired: 'Nom requis',
    phoneInvalid: 'Numéro invalide (ex: 0612345678)',
    cityRequired: 'Ville requise',
    addressRequired: 'Adresse requise',
    insufficientStockFor: 'Stock insuffisant pour: {items}',
    customerInfo: 'Vos informations',
    fullName: 'Nom complet *',
    phoneLabel: 'Téléphone *',
    cityLabel: 'Ville *',
    addressLabel: 'Adresse de livraison *',
    chooseCity: 'Choisir une ville',
    contactPreference: 'Préférence de contact *',
    whatsapp: 'WhatsApp',
    call: 'Appel',
    whatsappDesc: 'Message automatique',
    callDesc: 'Nous vous appelons',
    modify: 'Modifier',
    continue: 'Continuer',
    saving: 'Enregistrement...',
    confirmOrder: 'Confirmer la commande',
    orderReceived: 'Commande reçue !',
    thankYouOrder: 'Merci {name}, votre commande a bien été enregistrée.',
    orderNumber: 'Numéro de commande',
    orderDetails: 'Récapitulatif',
    openWhatsapp: 'Ouvrir WhatsApp',
    confirm: 'Confirmer',
    backToShop: 'Retour à la boutique',
    callDialogTitle: 'Nous allons vous appeler',
    callDialogDescription: 'Nous allons vous appeler bientôt pour confirmer votre commande. Assurez-vous que votre téléphone est disponible.',
    perfectThanks: 'Parfait, merci !',
    footerNavigation: 'Navigation',
    footerContact: 'Contact',
    footerBlurb: 'Découvrez nos soins naturels et l’art du hammam marocain, pensés pour une beauté éclatante.',
    whatsappContact: 'WhatsApp',
    phoneContact: 'Tél',
    emailContact: 'Email',
    emailAddress: 'hello@darnour.ma',
    rights: '© 2025 Dar Nour. Tous droits réservés.',
    madeWithLove: 'Fait avec ❤️ au Maroc',
    categoryAll: 'Tout',
    categoryPack: '✦ Packs',
    categoryIndividual: 'Individuels',
    adminPanel: 'Administration',
    logout: 'Déconnexion',
    dashboard: 'Tableau de bord',
    orders: 'Commandes',
    ordersToday: 'Commandes aujourd\'hui',
    needsAction: 'Nécessite action',
    totalOrders: 'Total commandes',
    noOrders: 'Aucune commande',
    noOrdersSearch: 'Essayez une autre recherche',
    searchOrdersPlaceholder: 'Rechercher par nom, téléphone, ville...',
    itemsLabel: 'article(s)',
    orderItems: 'Articles commandés',
    internalNote: 'Note interne',
    noNotes: 'Aucune note',
    save: 'Sauvegarder',
    cancel: 'Annuler',
    orderStatusPreparing: 'Préparation',
    orderStatusDispatched: 'Expédiée',
    orderStatusDelivered: 'Livrée',
    orderStatusCancelled: 'Annulée',
    orderStatusPending: 'En attente',
    orderStatusConfirmed: 'Confirmée',
    newProduct: 'Nouveau',
    productName: 'Nom du produit',
    productStock: 'Stock',
    featuredProduct: 'Produit en vedette (page d\'accueil)',
    categoryLabel: 'Catégorie',
    price2Label: 'Prix ×2',
    price3plusLabel: 'Prix ×3+',
    imageBefore: 'Image Avant',
    imageAfter: 'Image Après',
    descriptionLabel: 'Description',
    ingredientsLabel: 'Ingrédients',
    slugRequired: 'Slug requis',
    invalidPrice: 'Prix invalide',
    beforeAfterImagesRequired: 'Les deux images Avant et Après sont requises',
    createProduct: 'Créer le produit',
    updateProduct: 'Mettre à jour le produit',
    deleteProduct: 'Supprimer le produit',
    confirmDeleteProduct: 'Voulez-vous vraiment supprimer ce produit ?',
    deleteProductWarning: 'Cette action supprimera définitivement {name}. Cette opération est irréversible.',
    adminLoginTitle: 'Espace Administration',
    adminLoginSubtitle: 'Connexion sécurisée',
    emailLabel: 'Email',
    passwordLabel: 'Mot de passe',
    loginButton: 'Se connecter',
    loginLoading: 'Connexion...',
    orderConfirmedToast: 'Commande confirmée ! Votre panier a été vidé.',
    stockCheckError: 'Impossible de vérifier le stock. Réessayez plus tard.',
    genericError: 'Une erreur est survenue. Réessayez.',
    cartReview: 'Récapitulatif du panier',
    subtotal: 'Sous-total',
    orderConfirmed: 'Commande reçue !',
    orderSummary: 'Récapitulatif',
    cartEmptyMessage: 'Panier vide',
    noOrdersYet: 'Aucune commande',
    deleteConfirmation: 'Confirmation de suppression',
    confirmDelete: 'Confirmer',
    cancelDelete: 'Annuler',
    updateStatus: 'Mettre à jour le statut',
    whatsappContactText: 'WhatsApp',
    phoneContactText: 'Appel',
    orderNotePlaceholder: 'Note interne...',
    changeLanguage: 'Changer la langue',
  },
  en: {
    home: 'Home',
    shop: 'Shop',
    packs: 'Packs',
    cart: 'Cart',
    cartAria: 'Open cart',
    languageToggle: 'AR',
    brandTagline: 'Moroccan cosmetics',
    heroBadge: '✦ Authentic Moroccan cosmetics',
    heroTitleLine1: 'The Hammam Ritual',
    heroTitleLine2: 'Luxury',
    heroDescription: 'Rediscover the Moroccan hammam tradition with our natural care products made from Morocco’s beauty treasures.',
    discoverPacks: 'Discover our packs',
    individualProducts: 'Individual products',
    featuredSub: 'Our bestsellers',
    packsPopular: 'Popular packs',
    viewAllProducts: 'View all',
    viewAllProductsShort: 'View all products',
    viewAllOrders: 'View all orders',
    noNewOrders: 'No new orders',
    latestOrders: 'Latest orders',
    wrongCredentials: 'Incorrect email or password',
    prepareOrder: 'Prepare',
    dispatchOrder: 'Dispatch',
    deliverOrder: 'Deliver',
    cancelOrder: 'Cancel',
    statusAll: 'All',
    noProducts: 'No products',
    editProduct: 'Edit product',
    fillProductInfo: 'Fill in product information',
    mainImageUrlLabel: 'Main image (URL)',
    additionalImagesLabel: 'Additional images (one URL per line)',
    uploadProductImages: 'Upload product images',
    selectProductImages: 'Click to select images',
    selectBeforeImage: 'Select before image',
    selectAfterImage: 'Select after image',
    uploadBeforeImageLabel: 'Upload before image',
    uploadAfterImageLabel: 'Upload after image',
    productDescription: 'Description',
    productIngredients: 'Ingredients',
    productsTitle: 'Products',
    trustTitle: 'Trusted by',
    trustHeading: 'Customer reviews',
    review1Text: 'The Aker Fassi pack is amazing! My skin has never been so soft and radiant. Highly recommended.',
    review2Text: 'Exceptional quality, 100% natural products. The scrub is the best I have used. Fast delivery!',
    review3Text: 'I buy the Nila pack every month. The hair oil transformed my hair completely. Thank you Dar Nour!',
    review4Text: 'The plum oil brought back glow to my skin in just a few days.',
    review5Text: 'Attentive customer service and ultra-fast delivery. I love the hammam routine.',
    review6Text: 'The texture is divine and the scents are so calming. My friends asked me for the brand!',
    review7Text: 'My hair feels softer and stronger after only two uses of the pack. A true luxury treatment.',
    orderNowSectionTitle: 'Order Now',
    orderNowSectionText: 'Enjoy our exclusive bundle offers — the more you order, the more you save.',
    faqSub: 'Frequently asked',
    faqTitle: 'Clear answers for your ritual',
    faqDescription: 'Everything you need to know to choose the perfect Moroccan hammam care.',
    faqQuestion1: 'How long does delivery take?',
    faqAnswer1: 'We deliver across Morocco in 2–4 business days with full shipment tracking.',
    faqQuestion2: 'Are the products truly natural?',
    faqAnswer2: 'Yes, our formulas are crafted from authentic Moroccan ingredients with no parabens or sulfates.',
    faqQuestion3: 'Can I order a custom pack?',
    faqAnswer3: 'Absolutely — contact us on WhatsApp and we will tailor a ritual to your needs.',
    faqCardLabel: 'Premium FAQ',
    faqCardTitle: 'Your beauty routine, simplified',
    faqCardText: 'Explore quick answers inspired by customer confidence and real wellness rituals.',
    faqCardTag1: 'Fast delivery',
    faqCardTag2: 'Natural ingredients',
    faqCardStat: 'Satisfaction rate',
    faqCardStatText: '98% happy customers',
    ctaBadge: 'Special offer',
    ctaHeading: 'More care, more confidence',
    ctaText: 'Explore our best-selling bundles designed to elevate every step of your beauty ritual.',
    ctaStat1Label: 'Packs available',
    ctaStat1Value: '12+ options',
    ctaStat2Label: 'Customer rating',
    ctaStat2Value: '4.9/5',
    shopIndividual: 'Shop individual products',
    ctaHighlight: 'Best sellers',
    ctaHighlightTitle: 'Curated wellness rituals',
    ctaHighlightDescription: 'Each pack brings together the best of hammam tradition and Moroccan ingredients.',
    ctaFeature1: 'Why Dar Nour?',
    ctaFeature1Text: 'Express delivery and premium natural care',
    ctaFeatureBadge: '100% natural',
    viewOurPacks: 'View our packs',
    delivery: 'Morocco delivery',
    deliveryDesc: 'Across Morocco in 2–4 days',
    natural: '100% Natural',
    naturalDesc: 'Authentic Moroccan formulas',
    quality: 'Quality Guaranteed',
    qualityDesc: 'Satisfied or refunded',
    productNotFound: 'Product not found',
    returnToShop: 'Return to shop',
    back: 'Back',
    bestseller: 'Bestseller',
    priceLabel: 'Price',
    stockLabel: 'Stock',
    outOfStock: 'Out of stock',
    packBadge: '✦ PACK',
    twoUnits: '2 units: {price} MAD',
    threePlusUnits: '3+ units: {price} MAD',
    stockAvailability: 'Stock: {count} available',
    available: 'available',
    orderSection: 'Order',
    tierPricing: 'Tier pricing',
    quantity: 'Quantity',
    temporarilyUnavailable: 'Product temporarily unavailable',
    addToCart: 'Add to cart',
    orderNow: 'Order now',
    inYourCart: 'in your cart',
    ingredients: 'Ingredients',
    shopTitle: 'Our shop',
    searchPlaceholder: 'Search for a product...',
    noProductsFound: 'No products found',
    tryAnotherSearch: 'Try another search',
    productCountSingular: '1 product',
    productCountPlural: '{count} products',
    emptyCartTitle: 'Your cart is empty',
    emptyCartText: 'Discover our products and start your beauty ritual',
    discoverProducts: 'Discover products',
    myCart: 'My cart',
    summary: 'Summary',
    total: 'Total',
    continueShopping: 'Continue shopping',
    checkout: 'Checkout',
    cartStep: 'Cart',
    infoStep: 'Info',
    confirmStep: 'Confirmation',
    cartEmpty: 'Cart empty',
    nameRequired: 'Name required',
    phoneInvalid: 'Invalid phone number (ex: 0612345678)',
    cityRequired: 'City required',
    addressRequired: 'Address required',
    insufficientStockFor: 'Insufficient stock for: {items}',
    customerInfo: 'Your information',
    fullName: 'Full name *',
    phoneLabel: 'Phone *',
    cityLabel: 'City *',
    addressLabel: 'Delivery address *',
    chooseCity: 'Choose a city',
    contactPreference: 'Contact preference *',
    whatsapp: 'WhatsApp',
    call: 'Call',
    whatsappDesc: 'Automatic message',
    callDesc: 'We will call you',
    modify: 'Modify',
    continue: 'Continue',
    saving: 'Saving...',
    confirmOrder: 'Confirm order',
    orderReceived: 'Order received!',
    thankYouOrder: 'Thank you {name}, your order has been placed successfully.',
    orderNumber: 'Order number',
    orderDetails: 'Order summary',
    openWhatsapp: 'Open WhatsApp',
    confirm: 'Confirm',
    backToShop: 'Back to shop',
    callDialogTitle: 'We will call you',
    callDialogDescription: 'We will call you soon to confirm your order. Keep your phone available.',
    perfectThanks: 'Perfect, thank you!',
    footerNavigation: 'Navigation',
    footerContact: 'Contact',
    footerBlurb: 'Discover our natural care products and the art of the Moroccan hammam, designed for glowing skin.',
    whatsappContact: 'WhatsApp',
    phoneContact: 'Phone',
    emailContact: 'Email',
    emailAddress: 'hello@darnour.ma',
    rights: '© 2025 Dar Nour. All rights reserved.',
    madeWithLove: 'Made with ❤️ in Morocco',
    categoryAll: 'All',
    categoryPack: '✦ Packs',
    categoryIndividual: 'Individual',
    adminPanel: 'Admin panel',
    logout: 'Logout',
    dashboard: 'Dashboard',
    orders: 'Orders',
    ordersToday: 'Orders today',
    needsAction: 'Needs action',
    totalOrders: 'Total orders',
    noOrders: 'No orders',
    noOrdersSearch: 'Try another search',
    searchOrdersPlaceholder: 'Search by name, phone, city...',
    itemsLabel: 'item(s)',
    orderItems: 'Ordered items',
    internalNote: 'Internal note',
    noNotes: 'No notes',
    save: 'Save',
    cancel: 'Cancel',
    orderStatusPreparing: 'Preparing',
    orderStatusDispatched: 'Dispatched',
    orderStatusDelivered: 'Delivered',
    orderStatusCancelled: 'Cancelled',
    orderStatusPending: 'Pending',
    orderStatusConfirmed: 'Confirmed',
    newProduct: 'New',
    productName: 'Product name',
    productStock: 'Stock',
    featuredProduct: 'Featured product (homepage)',
    categoryLabel: 'Category',
    price2Label: 'Price ×2',
    price3plusLabel: 'Price ×3+',
    imageBefore: 'Before image',
    imageAfter: 'After image',
    descriptionLabel: 'Description',
    ingredientsLabel: 'Ingredients',
    slugRequired: 'Slug required',
    invalidPrice: 'Invalid price',
    beforeAfterImagesRequired: 'Both before and after images are required',
    createProduct: 'Create product',
    updateProduct: 'Update product',
    deleteProduct: 'Delete product',
    confirmDeleteProduct: 'Do you really want to delete this product?',
    deleteProductWarning: 'This will permanently delete {name}. This action is irreversible.',
    adminLoginTitle: 'Admin area',
    adminLoginSubtitle: 'Secure login',
    emailLabel: 'Email',
    passwordLabel: 'Password',
    loginButton: 'Log in',
    loginLoading: 'Logging in...',
    orderConfirmedToast: 'Order confirmed! Your cart has been emptied.',
    stockCheckError: 'Unable to verify stock. Please try again later.',
    genericError: 'Something went wrong. Please try again.',
    cartReview: 'Cart review',
    subtotal: 'Subtotal',
    orderConfirmed: 'Order received!',
    orderSummary: 'Order summary',
    cartEmptyMessage: 'Cart is empty',
    noOrdersYet: 'No orders yet',
    deleteConfirmation: 'Delete confirmation',
    confirmDelete: 'Confirm',
    cancelDelete: 'Cancel',
    updateStatus: 'Update status',
    whatsappContactText: 'WhatsApp',
    phoneContactText: 'Phone',
    orderNotePlaceholder: 'Internal note...',
    changeLanguage: 'Change language',
  },
  ar: {
    home: 'الرئيسية',
    shop: 'المتجر',
    packs: 'الباقات',
    cart: 'عربة التسوق',
    cartAria: 'عرض العربة',
    languageToggle: 'FR',
    brandTagline: 'مستحضرات تجميل مغربية',
    heroBadge: '✦ مستحضرات تجميل مغربية أصلية',
    heroTitleLine1: 'طقس الحمّام',
    heroTitleLine2: 'فاخر',
    heroDescription: 'اكتشفي تقاليد الحمّام المغربي مع منتجاتنا الطبيعية المصنوعة من كنوز الجمال المغربية.',
    discoverPacks: 'اكتشفي باقاتنا',
    individualProducts: 'منتجات فردية',
    featuredSub: 'الأكثر مبيعًا',
    packsPopular: 'الباقات الشهيرة',
    viewAllProducts: 'عرض الكل',
    viewAllProductsShort: 'عرض جميع المنتجات',
    viewAllOrders: 'عرض جميع الطلبات',
    noNewOrders: 'لا توجد طلبات جديدة',
    latestOrders: 'أحدث الطلبات',
    wrongCredentials: 'البريد الإلكتروني أو كلمة المرور غير صحيحة',
    prepareOrder: 'قيد التحضير',
    dispatchOrder: 'تم الإرسال',
    deliverOrder: 'تم التوصيل',
    cancelOrder: 'إلغاء',
    statusAll: 'الكل',
    noProducts: 'لا توجد منتجات',
    editProduct: 'تعديل المنتج',
    fillProductInfo: 'املأ معلومات المنتج',
    mainImageUrlLabel: 'الصورة الرئيسية (رابط)',
    additionalImagesLabel: 'صور إضافية (رابط واحد في كل سطر)',
    uploadProductImages: 'تحميل صور المنتج',
    selectProductImages: 'انقر لتحديد الصور',
    selectBeforeImage: 'تحديد صورة قبل',
    selectAfterImage: 'تحديد صورة بعد',
    uploadBeforeImageLabel: 'تحميل صورة قبل',
    uploadAfterImageLabel: 'تحميل صورة بعد',
    productDescription: 'الوصف',
    productIngredients: 'المكونات',
    productsTitle: 'المنتجات',
    trustTitle: 'يثقن بنا',
    trustHeading: 'آراء زبوناتنا',
    review1Text: 'باقة آكر فاسي رائعة! بشرتي لم تكن ناعمة ومشرقة بهذا الشكل من قبل. أنصح بها بشدة.',
    review2Text: 'جودة استثنائية، منتجات 100٪ طبيعية. المقشر هو الأفضل الذي استخدمته. التوصيل سريع!',
    review3Text: 'أشتري باقة نيلا كل شهر. زيت الشعر غيّر شعري تمامًا. شكرًا دار نور!',
    review4Text: 'زيت البرقوق أضفى إشراقة على بشرتي في أيام قليلة فقط.',
    review5Text: 'خدمة عملاء رائعة وتوصيل سريع جدًا. أحب روتين الحمّام.',
    review6Text: 'الملمس فخم والعطور مهدئة للغاية. طلبت مني صديقاتي اسم العلامة!',
    review7Text: 'شعري أصبح أنعم وأقوى بعد استخدام العبوة مرتين فقط. علاج فاخر حقيقي.',
    orderNowSectionTitle: 'اطلبي الآن',
    orderNowSectionText: 'استفيدي من عروض الباقات الحصرية — كلما طلبت أكثر، وفرت أكثر.',
    faqSub: 'أسئلة شائعة',
    faqTitle: 'إجابات واضحة لرشدك',
    faqDescription: 'كل ما تحتاجين معرفته لاختيار طقس الحمّام المغربي المثالي.',
    faqQuestion1: 'كم يستغرق التوصيل؟',
    faqAnswer1: 'نوصّل في جميع أنحاء المغرب خلال 2–4 أيام عمل مع تتبّع كامل للطلبية.',
    faqQuestion2: 'هل المنتجات طبيعية حقًا؟',
    faqAnswer2: 'نعم، تركيباتنا مصنوعة من مكونات مغربية أصلية بدون بارابين أو كبريتات.',
    faqQuestion3: 'هل يمكنني طلب باقة مخصصة؟',
    faqAnswer3: 'بالتأكيد — تواصلي معنا عبر واتساب وسنعد طقسًا مخصصًا لكِ.',
    faqCardLabel: 'الأسئلة المميزة',
    faqCardTitle: 'روتينك الجمالي مبسّط',
    faqCardText: 'اطّلعي على إجابات سريعة مستوحاة من ثقة الزبونات وتجارب العناية.',
    faqCardTag1: 'توصيل سريع',
    faqCardTag2: 'مكونات طبيعية',
    faqCardStat: 'نسبة الرضا',
    faqCardStatText: '98% من الزبونات راضيات',
    ctaBadge: 'عرض خاص',
    ctaHeading: 'العناية أكثر، ثقة أكبر',
    ctaText: 'اكتشفي باقاتنا الأعلى مبيعًا المصممة لترقية كل خطوة من طقس جمالك.',
    ctaStat1Label: 'الباقات المتاحة',
    ctaStat1Value: '12+ خيار',
    ctaStat2Label: 'تقييم الزبونات',
    ctaStat2Value: '4.9/5',
    shopIndividual: 'عرض المنتجات الفردية',
    ctaHighlight: 'الأكثر مبيعًا',
    ctaHighlightTitle: 'طقوس عناية منتقاة',
    ctaHighlightDescription: 'كل باقة تجمع أفضل تقاليد الحمّام والمكونات المغربية.',
    ctaFeature1: 'لماذا دار نور؟',
    ctaFeature1Text: 'توصيل سريع وعناية طبيعية مميزة',
    ctaFeatureBadge: '100% طبيعي',
    viewOurPacks: 'عرض باقاتنا',
    delivery: 'توصيل بالمغرب',
    deliveryDesc: 'في جميع أنحاء المغرب خلال 2–4 أيام',
    natural: '100٪ طبيعي',
    naturalDesc: 'تركيبات مغربية أصيلة',
    quality: 'جودة مضمونة',
    qualityDesc: 'راضيات أو مسترجعات',
    productNotFound: 'المنتج غير موجود',
    returnToShop: 'العودة إلى المتجر',
    back: 'عودة',
    bestseller: 'الأكثر مبيعًا',
    priceLabel: 'السعر',
    stockLabel: 'المخزون',
    outOfStock: 'غير متوفر',
    packBadge: '✦ باقة',
    twoUnits: '2 وحدة: {price} MAD',
    threePlusUnits: '3+ وحدات: {price} MAD',
    stockAvailability: 'المخزون: {count} متاح',
    available: 'متوفر',
    orderSection: 'اطلب',
    tierPricing: 'أسعار متدرجة',
    quantity: 'الكمية',
    temporarilyUnavailable: 'المنتج غير متوفر مؤقتًا',
    addToCart: 'أضف إلى السلة',
    orderNow: 'اطلب الآن',
    inYourCart: 'في سلتك',
    ingredients: 'المكونات',
    shopTitle: 'متجرنا',
    searchPlaceholder: 'ابحث عن منتج...',
    noProductsFound: 'لم يتم العثور على منتجات',
    tryAnotherSearch: 'حاول بحثًا آخر',
    productCountSingular: 'منتج واحد',
    productCountPlural: '{count} منتجات',
    emptyCartTitle: 'سلتك فارغة',
    emptyCartText: 'اكتشفي منتجاتنا وابدئي طقسك الجمالي',
    discoverProducts: 'اكتشفي المنتجات',
    myCart: 'سلتك',
    summary: 'الملخص',
    total: 'الإجمالي',
    continueShopping: 'متابعة التسوق',
    checkout: 'اطلب',
    cartStep: 'السلة',
    infoStep: 'المعلومات',
    confirmStep: 'التأكيد',
    cartEmpty: 'السلة فارغة',
    nameRequired: 'الاسم مطلوب',
    phoneInvalid: 'رقم غير صالح (مثال: 0612345678)',
    cityRequired: 'المدينة مطلوبة',
    addressRequired: 'العنوان مطلوب',
    insufficientStockFor: 'المخزون غير كافٍ لـ: {items}',
    customerInfo: 'معلوماتك',
    fullName: 'الاسم الكامل *',
    phoneLabel: 'الهاتف *',
    cityLabel: 'المدينة *',
    addressLabel: 'عنوان التوصيل *',
    chooseCity: 'اختر مدينة',
    contactPreference: 'طريقة الاتصال *',
    whatsapp: 'واتساب',
    call: 'مكالمة',
    whatsappDesc: 'رسالة تلقائية',
    callDesc: 'سنتصل بك',
    modify: 'تعديل',
    continue: 'متابعة',
    saving: 'جاري الحفظ...',
    confirmOrder: 'تأكيد الطلب',
    orderReceived: 'تم استلام الطلب!',
    thankYouOrder: 'شكرًا لك {name}، تم تسجيل طلبك بنجاح.',
    orderNumber: 'رقم الطلب',
    orderDetails: 'ملخص الطلب',
    openWhatsapp: 'افتح واتساب',
    confirm: 'تأكيد',
    backToShop: 'العودة إلى المتجر',
    callDialogTitle: 'سنتصل بك',
    callDialogDescription: 'سنتصل بك قريبًا لتأكيد طلبك. تأكدي من أن هاتفك متاح.',
    perfectThanks: 'حسنًا، شكرًا!',
    footerNavigation: 'التنقل',
    footerContact: 'التواصل',
    footerBlurb: 'اكتشفي منتجاتنا الطبيعية وفن الحمّام المغربي بتصاميم مميزة لبشرة متوهجة.',
    whatsappContact: 'واتساب',
    phoneContact: 'الهاتف',
    emailContact: 'البريد الإلكتروني',
    emailAddress: 'hello@darnour.ma',
    rights: '© 2025 دار نور. جميع الحقوق محفوظة.',
    madeWithLove: 'مصنوع بحب ❤️ في المغرب',
    categoryAll: 'الكل',
    categoryPack: '✦ باقات',
    categoryIndividual: 'فرادي',
    adminPanel: 'لوحة الإدارة',
    logout: 'تسجيل الخروج',
    dashboard: 'لوحة التحكم',
    orders: 'الطلبات',
    ordersToday: 'طلبات اليوم',
    needsAction: 'تتطلب إجراء',
    totalOrders: 'إجمالي الطلبات',
    noOrders: 'لا توجد طلبات',
    noOrdersSearch: 'حاول بحثًا آخر',
    searchOrdersPlaceholder: 'ابحث بالاسم أو الهاتف أو المدينة...',
    itemsLabel: 'منتج(ات)',
    orderItems: 'المنتجات المطلوبة',
    internalNote: 'ملاحظة داخلية',
    noNotes: 'لا توجد ملاحظات',
    save: 'حفظ',
    cancel: 'إلغاء',
    orderStatusPreparing: 'قيد التحضير',
    orderStatusDispatched: 'تم الإرسال',
    orderStatusDelivered: 'تم التوصيل',
    orderStatusCancelled: 'أُلغي',
    orderStatusPending: 'قيد الانتظار',
    orderStatusConfirmed: 'مؤكدة',
    newProduct: 'جديد',
    productName: 'اسم المنتج',
    productStock: 'المخزون',
    featuredProduct: 'منتج مميز (الصفحة الرئيسية)',
    categoryLabel: 'الفئة',
    price2Label: 'سعر ×2',
    price3plusLabel: 'سعر ×3+',
    imageBefore: 'صورة قبل',
    imageAfter: 'صورة بعد',
    descriptionLabel: 'الوصف',
    ingredientsLabel: 'المكونات',
    slugRequired: 'رابط قصير مطلوب',
    invalidPrice: 'سعر غير صالح',
    beforeAfterImagesRequired: 'يتطلب كلا الصورتين قبل وبعد',
    createProduct: 'إنشاء المنتج',
    updateProduct: 'تحديث المنتج',
    deleteProduct: 'حذف المنتج',
    confirmDeleteProduct: 'هل تريد حذف هذا المنتج؟',
    deleteProductWarning: 'سيتم حذف {name} نهائيًا. هذا الإجراء لا رجعة فيه.',
    adminLoginTitle: 'منطقة الإدارة',
    adminLoginSubtitle: 'تسجيل دخول آمن',
    emailLabel: 'البريد الإلكتروني',
    passwordLabel: 'كلمة المرور',
    loginButton: 'تسجيل الدخول',
    loginLoading: 'جاري تسجيل الدخول...',
    stockCheckError: 'لا يمكن التحقق من المخزون. حاول مرة أخرى لاحقًا.',
    genericError: 'حدث خطأ. يرجى المحاولة مرة أخرى.',
    orderConfirmedToast: 'تم تأكيد الطلب! تم تفريغ سلتك.',
    cartReview: 'ملخص السلة',
    subtotal: 'المجموع الفرعي',
    orderConfirmed: 'تم استلام الطلب!',
    orderSummary: 'ملخص الطلب',
    cartEmptyMessage: 'السلة فارغة',
    noOrdersYet: 'لا توجد طلبات',
    deleteConfirmation: 'تأكيد الحذف',
    confirmDelete: 'تأكيد',
    cancelDelete: 'إلغاء',
    updateStatus: 'تحديث الحالة',
    whatsappContactText: 'واتساب',
    phoneContactText: 'مكالمة',
    orderNotePlaceholder: 'ملاحظة داخلية...',
    changeLanguage: 'تغيير اللغة',
  },
} as const

type TranslationKey = keyof typeof translations['fr']

const LanguageContext = React.createContext<LanguageContextValue | null>(null)

const STORAGE_KEY = 'eco-language'

function getInitialLanguage(): Language {
  if (typeof window === 'undefined') return 'fr'
  const stored = window.localStorage.getItem(STORAGE_KEY)
  return stored === 'ar' ? 'ar' : stored === 'en' ? 'en' : 'fr'
}

function formatTranslation(value: string, params?: Record<string, string | number>) {
  if (!params) return value
  return value.replace(/\{(\w+)\}/g, (_, key) => String(params[key] ?? `{${key}}`))
}

export type LanguageContextValue = {
  language: Language
  setLanguage: React.Dispatch<React.SetStateAction<Language>>
  t: (key: TranslationKey, params?: Record<string, string | number>) => string
}

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = React.useState<Language>(getInitialLanguage)

  React.useEffect(() => {
    window.localStorage.setItem(STORAGE_KEY, language)
    document.documentElement.lang = language
    document.documentElement.dir = language === 'ar' ? 'rtl' : 'ltr'
  }, [language])

  const value = React.useMemo(
    () => ({
      language,
      setLanguage,
      t: (key: TranslationKey, params?: Record<string, string | number>) =>
        formatTranslation(translations[language][key], params),
    }),
    [language]
  )

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>
}

export function useLanguage() {
  const context = React.useContext(LanguageContext)
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider')
  }
  return context
}
